### PR TITLE
Fiverr redesign

### PR DESCRIPTION
**Pull request by BryanRam**

### CODE REVIEW

**Comment by BryanRam** [comment]
Here's the code for the redesign. Feel free to let me know if there's any questions or issues.

**Comment by sl5035** [comment]
Hey, just checked the fixed website. Everything looks good! You're still working with the wave part tho, right?

**Comment by BryanRam** [comment]
> Hey, just checked the fixed website. Everything looks good! You're still working with the wave part tho, right?

Oh sorry I forgot to add that commit. Just pushed that animation now.

**Comment by sl5035** [comment]
This is perfect! I can fix some minor bugs from now on. Thank you so much!

**Pull request merged**
